version: '3.8'

services:
  batch-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BATCH_ANALYZER_NAME=local-analysis
      - BATCH_ANALYZER_REPORT_PREFIX=page
      - CHROME_FLAGS=--headless --no-sandbox --disable-cache --disable-dev-shm-usage --disable-gpu
    volumes:
      # Mount local reports directory for persistence during development
      - ./reports:/app/reports
      # Mount custom URLs file if needed
      - ./urls.txt:/app/urls.txt:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
